name:                prose
version:             0.1.0.0
github:              "kalhauge/prose"
license:             BSD3
author:              "Christian Gram Kalhauge"
maintainer:          "christian@kalhauge.dk"
copyright:           "BSD-3"

extra-source-files:
- README.md
- LICENSE
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kalhauge/prose#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2
- megaparsec >= 9.0 && < 11
- prettyprinter >= 1.2
- parser-combinators
- mtl >= 2.2.2 && < 3
- template-haskell
- contravariant
- optparse-applicative
- pandoc-types >= 1.22
- aeson
- bytestring
- lens >= 4.19 && < 5

ghc-options: -Wall -haddock

library:
  source-dirs: src

executables:
  prose:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prose
    - optparse-applicative

tests:
  prose-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prose
    - Glob
    - base
    - doctest
    - hedgehog
    - hlint
    - hspec
    - hspec-discover >= 2.7
    - hspec-hedgehog
    - hspec-expectations-pretty-diff
    - tasty
    - tasty-hspec
    - tasty-rerun

